### ISSUE TITLE
Styling disrupts other SVG styling

### ISSUE THREAD

**Issue by ic-768** [jakobhoeg/enhanced-button#13]
In the buttonVariants styling, this size is applied to the svg's:
`[&_svg]:size-4 `

The problem is that this then doesn't let me style my other svg's in my project, as this takes precedence. It'd be great if we didn't target svg's globally.

**Comment by brunos3d** [comment]
### Reason

Its because my [latest PR](https://github.com/jakobhoeg/enhanced-button/pull/12). I updated the button styles to match with the latest variants of the original shadcn/ui button, as you can see [here](https://github.com/shadcn-ui/ui/blob/1081536246b44b6664f4c99bc3f1b3614e632841/apps/www/registry/default/ui/button.tsx#L8C289-L8C348), at the end of the line you will see these classes `[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0`.

This was implemented to avoid getting buttons with incongruent icon sizes.

### Solution

Just add the tailwind class size-5, or w-5 h-5 (if you are using old tailwind versions) with the important (! exclamation) syntax, it will enforce a different icon size. 

```tsx
<Button>
  <CalendarIcon className="!size-5" />
</Button>

// for old tailwind versions
<Button>
  <CalendarIcon className="!w-5 !h-5" />
</Button>
```

You can also remove these classes from your local button component.

Cheers

**Comment by jakobhoeg** [comment]
> ### Reason
> Its because my [latest PR](https://github.com/jakobhoeg/enhanced-button/pull/12). I updated the button styles to match with the latest variants of the original shadcn/ui button, as you can see [here](https://github.com/shadcn-ui/ui/blob/1081536246b44b6664f4c99bc3f1b3614e632841/apps/www/registry/default/ui/button.tsx#L8C289-L8C348), at the end of the line you will see these classes `[&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0`.
> 
> This was implemented to avoid getting buttons with incongruent icon sizes.
> 
> ### Solution
> Just add the tailwind class size-5, or w-5 h-5 (if you are using old tailwind versions) with the important (! exclamation) syntax, it will enforce a different icon size.
> 
> ```tsx
> <Button>
>   <CalendarIcon className="!size-5" />
> </Button>
> 
> // for old tailwind versions
> <Button>
>   <CalendarIcon className="!w-5 !h-5" />
> </Button>
> ```
> 
> You can also remove these classes from your local button component.
> 
> Cheers

Thanks for addressing the issue, Bruno!
