### ISSUE TITLE
A detail when pasting the button component

### ISSUE THREAD

**Issue by ivanosquis10** [jakobhoeg/enhanced-button#3]
First of all your idea is very cool and I love it. The situation is that when I paste the button component that you provide, I save and I get the following error, I have a project with a long and good development, I liked the idea and I wanted to implement some details in the buttons but I get this error...I will try to fix the error but I leave it here in case someone else has the same problem.
![image](https://github.com/jakobhoeg/enhanced-button/assets/83567373/128e7fc3-0c92-4a2c-a209-7cd4d7598757)

Updated: I think the problem is related to the prop "aschild".

**Comment by jakobhoeg** [comment]
Thank you for providing this information! I'll definitely look into it.

**Comment by thedevdavid** [comment]
It's because the `Slot` component from Radix can only accept 1 child component and now it may have more than that.
https://github.com/jakobhoeg/enhanced-button/blob/5e3be1f9890b307b5c89d815512e06cf58945534/src/components/ui/button.tsx#L83-L102

If you wrap everything inside `<Comp>` into a `<React.Fragment>`, it'll work. I've opened a PR https://github.com/jakobhoeg/enhanced-button/pull/4

**Comment by thedevdavid** [comment]
@jakobhoeg one thing to mention I just realized after making the PR: `asChild` prop does not work with `Fragment`.

So if the child is a `<Link>` from next.js for example, this won't work.

And it looks like an issue with Radix. https://github.com/radix-ui/primitives/issues/1825

So probably better to reorganize the Button component.
